.today-line {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 3px;
    background: red;
    z-index: 999;
}

.gantt-container {
    position: relative;
}
.task-progress {
    height: 100%;
    background: #16a34a;
    border-radius: 8px;
}

.progress-text {
    position: absolute;
    width: 100%;
    text-align: center;
    color: white;
    font-size: 12px;
    font-weight: bold;
}
.critical-task {
    background: red !important;
}
#dashboard{
 position:fixed;
 right:20px;
 top:20px;

 width:260px;

 background:white;

 border-radius:10px;

 padding:15px;

 box-shadow:0 2px 10px rgba(0,0,0,.1);
}